export const QUOTES = [
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Above all, don't lie to yourself.", author: "Fyodor Dostoevsky" },
  { text: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", author: "Jeremiah 29:11" },
  { text: "I can do all things through him who gives me strength.", author: "Philippians 4:13" },
  { text: "The Lord is my shepherd; I shall not want.", author: "Psalm 23:1" },
  { text: "In the world you will have tribulation. But take heart; I have overcome the world.", author: "John 16:33" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Iron sharpens iron, and one man sharpens another.", author: "Proverbs 27:17" },
  { text: "Be strong and courageous. Do not be frightened, and do not be dismayed.", author: "Joshua 1:9" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "A gem cannot be polished without friction, nor a man perfected without trials.", author: "Seneca" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Whatever your hand finds to do, do it with all your might.", author: "Ecclesiastes 9:10" },
  { text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle" },
  { text: "Let your eyes look directly forward, and your gaze be straight before you.", author: "Proverbs 4:25" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "God has not given us a spirit of fear, but of power and of love and of a sound mind.", author: "2 Timothy 1:7" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Be still, and know that I am God.", author: "Psalm 46:10" },
  { text: "Man conquers the world by conquering himself.", author: "Zeno of Citium" },
  { text: "Do not be conformed to this world, but be transformed by the renewal of your mind.", author: "Romans 12:2" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "If you faint in the day of adversity, your strength is small.", author: "Proverbs 24:10" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "Walk with the wise and become wise.", author: "Proverbs 13:20" }
];
