// src/types/financial_report.ts

import { Category, AuditResolution } from './accountant';

/**
 * A breakdown of spending for a single category.
 */
export interface SpendingAnalysisCategory {
  categoryId: string;
  categoryName: string;
  /** The total amount spent in this category according to the user's audit. */
  totalSpent: number;
  /** A brief, insightful summary (1-2 sentences) from the AI about this category. */
  aiSummary: string;
  /** A score from 1 (poor) to 10 (excellent) representing financial health in this area. */
  healthScore: number;
}

/**
 * The proposed budget for a single category.
 */
export interface ProposedBudgetCategory {
  categoryId: string;
  categoryName: string;
  allocatedAmount: number;
  subcategories: {
    subcategoryId: string;
    subcategoryName: string;
    allocatedAmount: number;
  }[];
}

/**
 * A single piece of actionable advice from the AI.
 */
export interface MoneyManagementTip {
  /** A short, clear title for the tip. */
  title: string;
  /** A detailed explanation of the tip and how to implement it. */
  description: string;
  /** The primary category this tip relates to (optional). */
  relatedCategoryName?: string;
  priority: 'high' | 'medium' | 'low';
}

/**
 * The comprehensive financial report generated by The Accountant AI (V2.0).
 */
export interface FinancialReport {
  /** A high-level summary of the user's financial situation. */
  executiveSummary: string;

  /** A detailed analysis of the user's spending habits based on their audit. */
  spendingAnalysis: SpendingAnalysisCategory[];

  /** The AI-generated monthly budget proposal. */
  proposedBudget: ProposedBudgetCategory[];

  /** Actionable advice and strategies for better money management. */
  moneyManagementAdvice: MoneyManagementTip[];

  /** Metadata for the report. */
  reportGeneratedAt: string; // ISO 8601
  version: '2.0';
}
